<lolspeak> 	    ::=	<noun_phrase> <verb> <noun_phrase> <adjective>
<noun_phrase>	::=	<article> <noun> <adjective>
<verb>	 	    ::=	lovez  |  hatez  | ates
<noun>	 	    ::=	dawg  |  kat  |  rat
<article>	    ::=	a  | teh
<adjective>     ::= fat | hungry | happy | mean